# Part of the Carbon Language project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

name: Dependent PR

on: [pull_request]

jobs:
  check_dependencies:
    runs-on: ubuntu-latest
    name: Check dependencies landed
    steps:
      - uses: gregsdennis/dependencies-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
